### PR TITLE
ros2: add curvature target marker

### PR DESCRIPTION
**Pull request by srmainwaring**
Add a marker to display the curvature target in addition to the position target. The length of the marker is the inverse curvature or turn radius. On straight segments the marker length is set to a small number (1.0E-6).

_Figure: Curvature marker shown as red arrow. The path following is from an experimental implementation in ArduPilot, and needs some further tuning._
curvature_marker

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@srmainwaring The closest point calculation still seems off on the last green segment. Do you know why the closest point is not on the path?

**Comment by srmainwaring** [comment]
> The closest point calculation still seems off on the last green segment. Do you know why the closest point is not on the path?

Didn't spot that, but you're correct. Not sure. Will need to look into that. Maybe the tolerance needs to be tighter with a smaller turn radius?

**Comment by Jaeyoung-Lim** [comment]
@srmainwaring Is this visible when we keep the minimum turn radius as before? Wondering if there is something hardcoded in hiding...

**Comment by srmainwaring** [comment]
@Jaeyoung-Lim, No. When I set the turn radius back to 80m I don't see the position target cutting across the turn. The behaviour is not linked to this PR, but the marker does help accentuate the issue.

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
